#!/bin/sh
if [ "$1" = "clean" ]; then
    rm -rf artifacts
    exit 0
fi

if [ artifacts/app -ot main.cpp ]; then
    mkdir -p artifacts
    echo "compiling ..."
    g++ -O3 main.cpp -fopenmp $(sdl2-config --cflags --libs) -o artifacts/app
fi

cd artifacts 
./app
cd ..
